### ISSUE TITLE
ready() is fired even when subscription is not fully loaded

### ISSUE THREAD

**Issue by andycjw** [numtel/meteor-mysql#11]
according to the readme, ready() is described as "Return boolean value corresponding to subscription fully loaded", but from what I see, ready() is returning true, even when the subscription is partially loaded.

**Comment by numtel** [comment]
Thanks, I was unaware of this issue. I guess that I never tested that it worked properly. I'll see what I can do.

**Comment by numtel** [comment]
@andycjw This should now be fixed.

**Comment by andycjw** [comment]
@numtel thanks, how does this code change work, why does using fut['return']() fixed this?
is fut['return']() same as fut.return()? I'm trying to learn how this work, but couldn't figure it out myself

**Comment by numtel** [comment]
@andycjw Yeah it's the same but because `return` is a reserved word, it's best to put it as a string (unless using ES6).

The reasoning behind this change can be traced back to [these 3 lines of code](https://github.com/meteor/meteor/blob/devel/packages/ddp/livedata_server.js#L991-993). Just an oversight on my part in the initial development.
