### ISSUE TITLE
subscription send full collection everytime instead of diff

### ISSUE THREAD

**Issue by andycjw** [numtel/meteor-mysql#12]
Unlike Mongo collection subscription, MysqlSubscription sends full data with new subsription id on each query, this makes things like infinite scroll impossible, like in example below

http://meteorpad.com/pad/JNMvanxS3f4BK7S5x/Template-Level%20Subs

the subscription sends full data, and it resets the template rendering for re-rendering from a new data, instead of appending new post to bottom.

did I do something wrong? or is it by design that it work differently from mongo collection?

**Comment by numtel** [comment]
Hmm that is an interesting issue, thank you for bringing this use case to my attention.

I have just released version 0.1.6 which adds a `change()` method to the `MysqlSubscription` prototype that allows changing the subscription's arguments after initialization.

Take a look at the `change_method` branch that I just posted on the leaderboard example repo:

https://github.com/numtel/meteor-mysql-leaderboard/commit/8b6343e26bd0f7dae707ce117d585683f3036f95

There may be some flickering though. This is due to the current diffing algorithm and the way its messages are sent. In the next few weeks, I will be upgrading the diffing algorithm to match the one that I've been using for my Postgres package which is currently under development.

**Comment by numtel** [comment]
Just released version 0.1.7 which fixes the flickering on the `change()` method.

**Comment by andycjw** [comment]
it now works perfectly, great commit!

**Comment by phibya** [comment]
I clone the `change_method` branch and change the parameter of subscription by using console:
`players.change(limit)`. Every time I call the `change()` method, it resets the collection and sends the whole collection (contains `limit` rows) to clients. Is there any way that the server pushes to clients only appended/removed/changed rows when changing the subscription parameter?
